project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    
  
website:
  title: ""

  navbar:
    title: BUSI 722
    search: true
    right:

      - text: Slide Decks
        file: slides.qmd

      - text: Code Binder
        href: https://mybinder.org/v2/gh/kerryback/2023-722-binder.git/HEAD

      - text: Assignments
        file: assignments.qmd

      - text: Home
        file: index.qmd

format: 
  html:
    theme: cosmo
    scss: styles.css
      



